### ISSUE TITLE
Running in windows?

### ISSUE THREAD

**Issue by antithing** [uzh-rpg/vilib#24]
Hi, i would like to use this on a windows OS, but the MakeFile gives me multiple errors. Would it be possible to supply a cMake option for building this lib?

Thanks!

**Comment by foehnx** [comment]
Dear @antithing 

Unfortunately we can not give any support for Windows since non of us if familiar with the development process on Windows.
However, @berndpfrommer (not affiliated) has just contributed a CMake config #23 that is now merged into master.
Probably take a look if this helps.

Good luck and let us know about the progress!

**Comment by berndpfrommer** [comment]
A word of caution: the cmake files have not been tested on Windows, nor do I develop on that platform.
